from _obsolete.ml.z_days_to_day_prediction_scripts import create_frames_for_invrec
from _obsolete.ml.z_days_to_day_prediction_scripts import run_frames_all
from _obsolete.ml.z_week_to_week_prediction_scripts import create_frames_for_weekly_invrec
from _obsolete.ml.z_week_to_week_prediction_scripts import run_frames_all